sudo: required
dist: trusty

language: java
jdk: openjdk8

script: "mvn deploy --settings depoly/settings.xml -B -Ptravis -DskipTests=false -Dmaven.javadoc.skip=false"

cache:
  directories:
  - "$HOME/.m2"
