sudo: required
dist: trusty

language: java
jdk: openjdk8

install: "/bin/true"
script: "mvn deploy --settings deploy/settings.xml -B -P travis-osshr -DskipTests=false -Dmaven.javadoc.skip=false"

cache:
  directories:
  - "$HOME/.m2"
  